export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED:"USER_DATA_EDITED",
    IMAGE_UPDATED:"IMAGE_UPDATED"
  },
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    LIKE:"POST_LIKE",
    COMMENT:"POST_COMMENT",
  },
};
